### ISSUE TITLE
Opera launcher does not work in Windows 7

### ISSUE THREAD

**Issue by barancev** [operasoftware/operaprestodriver#1]
Opera launcher does not work in Windows 7:
http://screencast.com/t/QZbOZrkO4

**Comment by wilhelm** [comment]
Thanks a lot for your feedback!

I am, however, not able to reproduce this problem on the Windows 7 (64-bit) machine I have here.

Which version with which updates are you running?

**Comment by barancev** [comment]
I'm using Windows 7 Enterprise version 6.1 build 7600, 32-bit
All official updates published into Windows Update are installed.
I've checked on two computers where this OS is installed.

Morover, I've attempted to run the launcher in VirtualBox with Windows XP SP3 (32-bit) and got the same error.

How can I provide more information to you for debugging?

Regards,
Alexei

**Comment by andreastt** [comment]
According to Microsoft, you're using an outdated Command.com file.  Please see this: http://support.microsoft.com/kb/245184

This looks like an issue in Windows, and not OperaDriver.  Let us know if you're not able to resolve it. (-:

**Comment by barancev** [comment]
Are you joking? I've created a new clean out-of-the-box installation of Windows XP, and you say it is broken and want me replace command.com. No-no-no!!! :)

May be you have publiched to github improper version of win32-launcher? The fact that it starts with ntvdm.exe means that it is old-scool 16-bit DOS application. Isn't it possible to build true 32-bit version of the launcher?

**Comment by andreastt** [comment]
Hm, it appears to be a proper 32-bit Windows application:

● file launcher-win32-i86pc.exe 
launcher-win32-i86pc.exe: PE32 executable for MS Windows (console) Intel 80386 32-bit

**Comment by barancev** [comment]
Oh! That was my trouble -- github saved an html page when I attempted to save exe file (launchers are not included in distr so I've downloaded them from source tree).

But I still have another problem:
"The program can't start because MSVCP100.dll is missing from your computer. Try reinstalling the program to fix this problem."

What additional packages required to run the launcher?

**Comment by wilhelm** [comment]
Try installing this package:

http://www.microsoft.com/downloads/en/details.aspx?FamilyID=a7b7a05e-6de6-4d3a-a423-37bf0912db84

**Comment by barancev** [comment]
Launcher works like a charm! Thanks!
