### ISSUE TITLE
Can not run launcher-win32-i86pc.exe on Windows XP

### ISSUE THREAD

**Issue by mpucholblasco** [operasoftware/operaprestodriver#11]
Hi everyone,
I'm trying to test my Selenium 2 tests in Opera, exactly on Windows XP.

My tests are written in Java. And, to test the connection to Opera, only 'WebDriver driver = new OperaDriver();' is executed.

When I execute previous code, the following exception appears:

Could not start the process : Cannot run program 'C:\Documents and Settings\User.launcher\launcher-win32-i86pc.exe'. No se pudo iniciar la aplicación porque su configuración es incorrecta. Reinstalar la aplicación puede solucionar el problema (in english: Can not initiate the application because your configuration is incorrect. Reinstall the application could solve the problem.).

I have executed the 'launcher-win32-i86pc.exe' file directly and the same error appears.

Reading from internet, I have discovered that Visual C++ redistributable package is needed, and I have installed it, but it did not solve the problem. Is anything more needed?

Thanks in advance.

**Comment by andreastt** [comment]
This is related to a missing C++ library in Windows.  Can you verify that you installed this package?

http://www.microsoft.com/downloads/en/details.aspx?FamilyID=a7b7a05e-6de6-4d3a-a423-37bf0912db84

**Comment by mpucholblasco** [comment]
Yes, it is verified, I have installed the package that you are telling me.

In fact, I have tested to execute it as root, but I have obtained the same result.

In http://dl.dropbox.com/u/28662366/Screenshot%20-%20Opera.png you can see a screenshot that proves it.

Regards.

**Comment by robbiewareham** [comment]
Hi,

I am having this same issue;

Windows XP
Opera 11.5
Webdriver 2.0.0

**Comment by Stuk** [comment]
We're looking into this, but haven't so far been able to reproduce internally. I'll get back to you when we know more

**Comment by mpucholblasco** [comment]
Ok, thanks.

2011/7/14 Stuk <
reply@reply.github.com>

> We're looking into this, but haven't so far been able to reproduce
> internally. I'll get back to you when we know more
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/operasoftware/operadriver/issues/11#issuecomment-1569024

## 

Marcel Puchol Blasco
mpucholblasco@gmail.com

**Comment by Stuk** [comment]
I've managed to reproduce it, and got it working by installing the 2008 redistributable: http://www.microsoft.com/download/en/details.aspx?displaylang=en&id=29

Could you try that?

**Comment by robbiewareham** [comment]
Okay, the launching now works but I am getting the following webdriver error;

```
Problem encountered : DISCONNECTED
```

Any thoughts?

-----Original Message-----

**Comment by andreastt** [comment]
Stuart: Are you saying we have the wrong dependency in our documentation, and that opera-launcher was compiled with Visual Studio 2008 rather than 2010?

**Comment by Stuk** [comment]
@robbiewareham when do you get this message? When you start running the script?

@andreastt yep, we need to update the docs to say 2008 redist

**Comment by andreastt** [comment]
The launchers in OperaDriver have now been updated and should be statically linked.  Closing this.
