### ISSUE TITLE
Can't return array of nodes using JavascriptExecutor.executeScript

### ISSUE THREAD

**Issue by ph--** [operasoftware/operaprestodriver#14]
Hi,

I'm trying to make this code work, but it gets stuck at the second line :
JavascriptExecutor js = (JavascriptExecutor) this.driver;
List&lt;WebElement&gt; divs = (List&lt;WebElement&gt;) js.executeScript("return [document.createElement('div'), document.createElement('div')]");

Nothing happens, it's just blocked.

These three cases work :
- WebElement div = (WebElement) js.executeScript("return document.createElement('div')");
- List&lt;String&gt; testStrings = (List&lt;String&gt;) js.executeScript("return ['pouet', 'pouet1'];");
- String testString = (String) js.executeScript("return 'pouet';");

The first one returns a node, the second returns an array of strings, the last one returns a String.
But the array of nodes doesn't work. It works perfectly in Firefox using FirefoxDriver.

This code is just an example. What I'm trying to do is getting nodes using a CSS selector with a ":contains" pseudo-class. But this pseudo-class is not implemented in WebDriver (more details about this : http://prototypic.net/blog/creating-a-sizzle-css-selector-handler-for-selenium2webdriver-in-java/), so I have to use Javascript (I'm not using this Sizzle class).

Thanks.
# 

I use : 
- Opera Next 11.50 b1074 (Linux, i686) ;
- selenium-server-standalone-2.2.0.jar (doesn't work either with selenium-server-standalone-2.1.0.jar) ;
- OpenJDK Runtime Environment (IcedTea6 1.9.2) (6b20-1.9.2-0ubuntu2)
- OpenJDK Client VM (build 19.0-b09, mixed mode, sharing)

This is how I instanciate the driver :
OperaDriverSettings settings = new OperaDriverSettings();
settings.setOperaBinaryLocation(System.getProperty("opera.launcher")); // path to opera-next
settings.setOperaLauncherListeningPort(63411);
this.driver = new OperaDriver(settings);

**Comment by Stuk** [comment]
Reproduced here. OperaDriver is going into an infinite loop getting the values in the array. Working on a solution now.

**Comment by Stuk** [comment]
This is now fixed in master, 6660b33

**Comment by ph--** [comment]
Thanks :)

Do you know when it will be included in the Selenium standalone server ?

**Comment by Stuk** [comment]
We aim to make another release this week, which should get included in the next Selenium release (which are happening weekly now).
