### ISSUE TITLE
contextClick will throw InvalidCoordinatesException

### ISSUE THREAD

**Issue by jumperchen** [operasoftware/operaprestodriver#15]
For example,

new Actions(driver).contextClick(element).perform();

**Comment by Stuk** [comment]
Could you provde an html page and script that causes this problem (paste at http://gist.github.com )? I couldn't reproduce with the page here: https://github.com/operasoftware/operadriver/blob/master/test/fixtures/test.html and the following script:

```
driver.get("http://localhost/fixtures/test.html");
WebElement el = driver.findElement(By.id("input_email"));
new Actions(driver).contextClick(el).perform();
```

**Comment by andreastt** [comment]
@jumperchen: Did this solve your problem?

**Comment by jumperchen** [comment]
Sorry for the late response.
The issue was gone after upgrade the new operadriver version.
