### ISSUE TITLE
sendKeys(Keys.LEFT_CONTROL + "a"/"x"/"c"/"v") doesn't work

### ISSUE THREAD

**Issue by jumperchen** [operasoftware/operaprestodriver#16]
As discussed in this - http://groups.google.com/group/webdriver/browse_thread/thread/69e9ddfad8dcb1e6

If we want to simulate copy & paste in web driver, all of the web drivers work as expected except Opera Driver.

**Comment by Stuk** [comment]
Thanks for the report. This is now fixed in 571f1144f004caed56be
