### ISSUE TITLE
Opera versions supported?

### ISSUE THREAD

**Issue by lkende** [operasoftware/operaprestodriver#24]
Not sure where else to ask this question, so posting here in the issue list.  

What is the officially supported Opera versions for OperaDriver?  The Selenium Wiki says only 11.5 and higher is supported, but I don't see this indicated on ReadMe.markdown ( nor the main page here on github for operadriver).  
## When I look through changes.markdown, I see where at one point earlier versions were supported:

2011/06/27 OperaDriver 0.5.1
Bug fixes

Core Scope service no longer required, to support earlier Opera versions. (stuartk)
## Shutdown Scope services in alternate way to support earlier Opera versions. (stuartk)

...but there's no mention of a version that stopped this support.

I always test on earlier versions of browsers with Selenium regardless of documentation because I need to test a wide base of browsers and on various platforms, both old and new.  Currently I have working versions (for the most part) of 10.60 and 10.50 on Windows, but they do have odd issues now and again on certain sites. 

I'd love it if support for 9.6 and above were a possibility but I understand that STP/0 is not supported. Maybe 10 and above?

Thanks.

**Comment by andreastt** [comment]
Only 10.5 and higher is supported out-of-the-box.  The earlier versions of Opera, maybe as early as 10, will work but you'll have to do a lot of manual work to get it running automatically.

The problem with Desktop Opera is that we've been missing a few command-line switches to enable scope testing on startup, specifying a clean profile, and so on.  All of these features will be supported in Opera 12.

**Comment by andreastt** [comment]
I did some more research on which Opera versions we support, and compiled this list on the wiki: http://code.google.com/p/selenium/wiki/OperaDriver#Supported_Opera_versions

We officially support Opera Desktop >= 11.00, but as I mention in a comment there it _might_ be possible to get it working with even older versions, possibly as low as 10.60.

Hopefully this should help. (-:

**Comment by lkende** [comment]
Excellent.  Thanks for researching and clarifying this!  

As I said, I have a 10.50 version working but the 10.xx versions tend to be a bit flaky.  The other thing you have to watch out for on these versions since they don't run with the -autotestmode flag is trying to change opera preferences via the webdriver.  I've actually written my own class for editing Opera profile settings.  Also, these older versions almost never work with basic authentication since there's no way I can see to turn off the prompt for user/pass even when the URL structure includes it.  

If you guys ever want some URLs to test that can give OperaDriver grief, let me know.  We test 1000s of URLs a month.  It's hard to make every webdriver work for every possible site out there.  Once I have these issues eliminated from my end I may communicate more on this.  Thanks!
