### ISSUE TITLE
sendKeys fails on Mac OSX, Opera 11.5 By.id, By.name, or By.xpath

### ISSUE THREAD

**Issue by lkende** [operasoftware/operaprestodriver#27]
Mac OS X 10.6, the Opera 11.5 version, a WebElement fails to sendKeys or Click after retrieving element. Not receiving an error message, just not actually functioning on the browser.

Using Selenium 2.6.0, which I believe is using the latest OperaDriver version release.

I discovered this during tests of my sites, but tested this on yahoo as well:

URL:  https://login.yahoo.com/config/login
username element: id=username,  name=username, or  //input[@name='username']
password element: id=passwd, name=passwd, or //input[@name='passwd']
submit element: id=.save, name=.save, or //button[@name='.save']

This was working in earlier release, the one in Selenium 2.4.0

**Comment by lkende** [comment]
Actually click() works mostly, but not sendKeys() upon closer inspection.

**Comment by andreastt** [comment]
Ikende, is this still valid for 0.9?  I've heard stories that OperaDriver on Mac needs Opera to stay in focus for interaction to work.

**Comment by lkende** [comment]
I can't answer this at the moment.  The logic in my class that uses the abstracted driver for all browser operations has a separate path for Opera where it uses a javascript approach for inserting text to input fields and submitting.  Upgrading to a newer version of selenium is not trivial.  Which version of selenium incorporates OperaDriver 0.9?

**Comment by andreastt** [comment]
Selenium 2.17 has OperaDriver 0.9.
