### ISSUE TITLE
Deploy to Maven Central

### ISSUE THREAD

**Issue by wakaleo** [operasoftware/operaprestodriver#35]
Could you make this dependency available on Maven central? It would make it much easier to generalize its use.

**Comment by andreastt** [comment]
We'll be deploying a new version of OperaDriver on Maven Central early next week. (-:

**Comment by wakaleo** [comment]
Awesome! As soon as it's available I'll integrate it into Thucydides.

On 13 November 2011 14:55, Andreas Tolf Tolfsen <
reply@reply.github.com

> wrote:
> 
> We'll be deploying a new version of OperaDriver on Maven Central early
> next week. (-:
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/operasoftware/operadriver/issues/35#issuecomment-2722381

## 

---

John Smart | Wakaleo Consulting  |  +64 21 032 2797
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
