### ISSUE TITLE
wait time set to 0 in findElement

### ISSUE THREAD

**Issue by polyzois** [operasoftware/operaprestodriver#36]
In class OperaDriver on row 1166:

OperaIntervals.WAIT_FOR_ELEMENT.setValue(0L);

This destroys the setup of my driver:

driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);

**Comment by andreastt** [comment]
Fixed in f86646a8cccadc304d9a2c2df733eb8ff0e24a14.  Thanks for the heads up!
