### ISSUE TITLE
Opera Launcher on Windows 7

### ISSUE THREAD

**Issue by lkende** [operasoftware/operaprestodriver#4]
Having trouble getting Opera to launch from Examples.  Had to manually add Opera environment vars in windows 7 for OPERA_PATH and OPERA_LAUNCHER and still had to hardcode the path to the binary launcher in OperaPaths.java and recompile.  Once I got past these issues, I've been stuck on getting it to launch the latest version of Opera 11.11 that I just installed two days ago.   I set the "Proxy Auto Connect" to on in the Developer config and Opera gives me no issues launching directly.

When I run the Example class, I get the message:

"Opera has failed to access or upgrade your profile. This may have occurred because your computer has insufficient resources available or because some files are locked by other applications. You may have to restart your computer before Opera will start again."

I've tried allowing "Everyone" full access in to both the operaprefs.ini and the operadefaultprefs.ini and at this point am at a loss as to what to do next.  

Not sure if this is a bug as I see an issue that someone else had on Windows 7 was corrected once he downloaded the executable correctly.  Any assistance is appreciated.  

Thanks,

Luke

Using Windows 7, 64-bit and Java 1.6.24

**Comment by Stuk** [comment]
Hi lkende, thanks very much for the report.

We've seen this internally recently but are not sure what's causing it. Out of interest, how are you launching the example, with `ant example` or through an IDE?

And to confirm, this is just with the regular example, not with OperaDesktopDriver?

**Comment by Stuk** [comment]
We've discovered this is related to the `-autotestmode` flag OperaDriver sets for Opera. It's being looked into and I'll keep you updated. In the mean time you could try an older version, available here: http://www.opera.com/browser/download/?os=windows&list=all

**Comment by lkende** [comment]
Well, I had a coworker experiment with this and he was able to get past the issue by running the command prompt as administrator on Win7.  This worked for me as well. 

 I have been just compiling and running on the command line but also had tried with Eclipse.  Yes, just the regular example.

**Comment by Stuk** [comment]
Good stuff. The problem is that the `-autotest` flag creates a new profile to ensure testing doesn't mess up your real one, and if the permissions aren't correct you'll get the error above. So yep, running as administrator will let it work.

**Comment by lkende** [comment]
So do you have to use the -autotest flag?  We are running the unit tests on a machine that is only used for testing. Meaning, there's no need for a separation between profiles.  As a matter of fact, I've been having trouble with the case where I need to specify Opera preferences that then are not applied when OperaDriver launches the browser.   It would also help if I didn't have to run as administrator.  I will look through the source code and see if this is something I can turn off, but thought I'd run it by you as well.

**Comment by Stuk** [comment]
The `-autotest` flag disables some dialogs that pop up, such as the crash recovery dialog, automatically enables the Proxy auto-connect option and ensures there's a Javascript context to use.

It can be disabled here https://github.com/operasoftware/operadriver/blob/master/src/com/opera/core/systems/runner/launcher/OperaLauncherRunner.java#L118 but any changes you make are unsupported ;)

Someone's looking in to the administrator problem. **Edit**: Apparently happens if you have Opera installed in a not-writable location. Seeing as you have a dedicated test box you could change the permissions on the Opera directory or install Opera somewhere else?

What issues with the preferences are you having?

**Comment by lkende** [comment]
Specifically, I 'm performing screenshots and needed the browser maximized but the launcher kept opening it at a smaller size even though manually launching Opera was showing up maximized. 

 I have 'Allow resizing and moving of browser" turned on in preferences, but calling javascript window.resizeTo does not work on Opera 11.11 unless it's a javascript created window (according to search results).  The only way I could get around this was that Opera "remembers" it's last size somewhere, so when the driver launched the browser automatically, I snuck in and manually hit the maximize button and it appears to open maximized now... didn't see where else in the settings I could affect this.  

After I sent that last message, I see that there is an object for prefs, so if I need to turn on or off other options, looks like I can programmatically adjust these, but haven't tried yet.

Yes, I can change the Opera folder permissions.  But if put somewhere else, the OperaPaths doesn't know where to find it.  I should mention that it isn't just one test box but multiple VMware images.  Plus Opera installed itself in folder called "Opera 11.00 Beta" which isn't found by OperaPaths unless you set an environment variable on windows.  When I finish the Selenium script I am writing, it will process on multiple VMware instances, windows, linux, and mac, so trying to make everything happen in the driver code and not have to tweak too many settings on each OS.

Thanks for your help.  Just glad there's an Opera driver at all, even if takes a little finagling.

**Comment by Stuk** [comment]
I've just updated the readme with some more information. https://github.com/operasoftware/operadriver/blob/master/README.txt Hopefully that will help, let me know if anything is unclear.

**Comment by lkende** [comment]
Here's two things that I have to do to get OperaDriver to work (I'm using the latest v0.5.1) on Win7.  Setting the OPERA_PATH environment variable does not appear to work consistently - at least not to the point of Opera 11 actually launching.  First I have to always rename my folder from "c:\program files\opera 11.xx\" to "c:\program files\opera".  Now, I had already set the Proxy Auto Connect flag in the standard profile, but now I find that I also had to launch opera.exe with the -autotestmode flag and then set Proxy Auto Connect again to get it to work.

What I mean is that you say "The -autotest flag ... automatically enables the Proxy auto-connect option " but I'm seeing a case where I have to go in and set it that way". So are you sure that this automatically gets set by using that flag?

**Comment by lkende** [comment]
Ok, was on vacation for a couple of weeks but getting back to this.

Here's my current scenario:
- I've upgraded to operaDriver v0.5.2 on Windows 7 (32-bit)
- I'm using Opera 11.00 which is installed in c:\program files\opera 11.00 beta\opera.exe.
- If I pass in this path via OperaDriverSettings.setOperaBinaryLocation() or set OPERA_PATH to this, then opera will launch but throws exception: org.openqa.selenium.WebDriverException: Could not find a runtime for script injection.
- If I programatically, rename c:\program files\opera 11.00 beta\opera.exe to  c:\program files\opera\opera.exe, that's when it appears to lose profile reference and when launch c:\program files\opera\opera.exe -autotestmode on command line, I have to go in and set the Proxy Auto Connect flag again, save and close.  Then the next time I run the driver it will work.

My main question or related issue would be why the WebDriverException is being thrown when the path is other than what would normally be expected.

**Comment by lkende** [comment]
Just to round this issue out.

After experimenting and understanding how this works a little better, I am able to set the path to the binary using the settings object:

OperaDriverSettings settings = new OperaDriverSettings();
settings.setOperaBinaryLocation(pathToOpera);
WebDriver driver = new OperaDriver(settings);

(I'm actually able to use this with some older versions of Opera 10.5, 11.00, just depends on version, platform and whether it's flaky or not)

Now, if I want to use the driver with abilities to set preferences before launching the browser, I have to use:

OperaDriver driver = new OperaDriver(settings);

..since WebDriver does not have methods for setPref();

What confused me before is that I am using this on locked images of Virtual machines... meaning, the first time I run OperaDriver on a browser that doesn't have Proxy Auto Connect already set on, it doesn't matter that I had it turned on for the default profile, I need to set it again for the auto-test profile. I found I can do that via preferences and automate it with...

operaDriver.setPref("Developer Tools","Proxy Auto Connect","1");

This is roughly what I've done to get things working... in versions prior to 11, I have to use my own methods for editing the profile, of course that's because earlier version don't recognize the -autotestmode flag and therefore don't create a special profile.
