### ISSUE TITLE
Browser is not closed when calling WebDriver#close()

### ISSUE THREAD

**Issue by scrobbleme** [operasoftware/operaprestodriver#42]
When the method WebDriver#close() is called on the OperaWebDriver the browser is not closed, but only the current tab (the first time I see Opera without any tab).

This makes it impossible to test multiple Opera versions through one test suite.

**Comment by andreastt** [comment]
The WebDriver interface says that WebDriver.close() should close the currently activated (focused) window.  If that is the last window, the browser instance should be quit.

I've addressed this now in 961324ef9b4c758e4ba94bcb435529bdf2d54bb9.

Thank you for reporting the bug (-:

**Comment by scrobbleme** [comment]
Works now. Thanks for the fix.
