### ISSUE TITLE
org.openqa.selenium.WebDriverException: Unable to extract bundled launcher: Unknown file: null

### ISSUE THREAD

**Issue by java-developer** [operasoftware/operaprestodriver#47]
Hello,

I am trying to run Selenium tests using OperaDriver but they fail to launch because it cannot find the launcher.

I've tried specifying the location as follows but it didn't work:

```
final DesiredCapabilities capabilities = DesiredCapabilities.opera();
capabilities.setCapability("opera.launcher", "/path/to/launcher-mac");
final OperaDriver driver = new OperaDriver(capabilities);
```

The only way I have been able to make it work is by putting a breakpoint on line 88 of OperaLauncherRunnerSettings and modifying the value of the "path" variable.

Environment:

OS: OSX 10.7.2
Selenium: 2.15.0
OperaDriver: 0.8.1

StackTrace:

org.openqa.selenium.WebDriverException: Unable to extract bundled launcher: Unknown file: null
Build info: version: '2.13.0', revision: '14794', time: '2011-11-18 17:49:47'
System info: os.name: 'Mac OS X', os.arch: 'amd64', os.version: '10.7.2', java.version: '1.7.0-u2-b21'
Driver info: driver.version: OperaDriver
at com.opera.core.systems.runner.launcher.OperaLauncherRunnerSettings.launcherPath(OperaLauncherRunnerSettings.java:97)
at com.opera.core.systems.runner.launcher.OperaLauncherRunnerSettings.getLauncher(OperaLauncherRunnerSettings.java:47)
at com.opera.core.systems.runner.launcher.OperaLauncherRunnerSettings.makeLauncherExecutable(OperaLauncherRunnerSettings.java:190)
at com.opera.core.systems.runner.launcher.OperaLauncherRunner.<init>(OperaLauncherRunner.java:120)
at com.opera.core.systems.OperaDriver.<init>(OperaDriver.java:295)

I hope someone can help.

Thanks,

Craig

**Comment by andreastt** [comment]
I think this might be related to issue #38.  If you look at the stack trace, it calls makeLauncherExecutable() from OperaDriver:295 before the launcher itself has been installed on the system.  This check works fine if you already have a launcher on your system, but fails whenever you try running OperaDriver for the first time.

As you will see from my last commen ton issue #38, I've disabled this check in HEAD.  Are you able to verify whether this works for you by checking out OperaDriver HEAD?  (You can use `ant jar` to build it.)

**Comment by java-developer** [comment]
This worked perfectly. Thank you for your help :)

When will this change be available via Maven? I don't like having a hard-coded JAR :)

**Comment by andreastt** [comment]
This will make it in to 0.9, which with a little luck should be out later this week. (-:

**Comment by java-developer** [comment]
Perfect, thanks :)
