### ISSUE TITLE
Maven Repository

### ISSUE THREAD

**Issue by andywuest** [operasoftware/operaprestodriver#6]
Hi, 
is it possible to provide the operadriver (releases/snapshots) via a maven repository? 
That would be a much more convenient way to get the files.

thanks in advance,
cheers,
Andy

**Comment by Stuk** [comment]
Yep, this is planned. Michael Tamm has offered to [help out](http://groups.google.com/group/selenium-developers/msg/812164e8c0f34948?hl=en), and will be working on a pom.xml in [his fork](https://github.com/MichaelTamm/operadriver), which I will merge when done.

**Comment by andreastt** [comment]
Now that OperaDriver is a part of Selenium WebDriver, is there a need for supplying OperaDriver as a separate repo in maven?

**Comment by andywuest** [comment]
Under http://mirrors.ibiblio.org/pub/mirrors/maven2/org/seleniumhq/selenium/ there are listed all the driver that are provided out of the box. however i cannot find the opera driver there. Unfotunately i cannot follow you, because i do not see that the opera driver is part of the selenium webdriver. Which package of selenium is supposed to contain the OperaDriver class?

**Comment by andywuest** [comment]
update of my last post: selenium-server-standalone-2.0rc2.jar does contain the OperaDriver however this is no real help, since most people will use the maven repositories with maven or an/ivy as build tool and use that for dependency resolution. people will use the fine granular maven depenencies, that can be found in the maven repository that i mentioned in my last post. if you need help with the maven repository, i can help you.

**Comment by rombert** [comment]
I am interested in a maven artifact as well.

**Comment by Stuk** [comment]
We're hoping to release a new version this week which I will be uploading to the Sonatype repo

**Comment by Stuk** [comment]
OperaDriver 0.6 has now been released, and should be soon synced to Sonatype central. The dependency XML is

```
<dependency>
  <groupId>com.opera</groupId>
  <artifactId>operadriver</artifactId>
  <version>0.6</version>
</dependency>
```
