### ISSUE TITLE
Race Condition

### ISSUE THREAD

**Issue by semperos** [operasoftware/operaprestodriver#62]
I'm using the Java API with Selenium-WebDriver 2 to test against Opera. My setup:
- Mac OSX Lion
- OperaDriver 0.9
- Selenium-WebDriver 2.16.0
- Opera 11.6

When I find a link using XPath, click on it, and then check the current URL of the driver, I get different results. By default, I get the URL of the driver _before_ I clicked on the link. If I add a Thread sleep call in my code (e.g., for 1000 milliseconds), then OperaDriver returns the correct URL of the page _after_ the link is clicked.

I have not seen this issue with Firefox or Chrome drivers.

**Comment by andreastt** [comment]
Do you have a reproducible test case?
