### ISSUE TITLE
Incorrect behavior of Opera browser for sendkeys commands

### ISSUE THREAD

**Issue by DFM86** [operasoftware/operaprestodriver#63]
Latest stable Opera on WinXP, Vista or Linux, Selenium java and server 2.19 (operaDriver 0.10,  latest).
I.'m testing one russian search engine. Tests contains a lot of Cyrillic and special symbols. And after 4th test opera thinks that hotkey was pressed (like zoom or ctrl+F). And all tests from "send keys" comes to Find bar in opera instead of search field from my site.

here are this test:

"К нам на утренний рассол"
"Прибыл \* посол"
полгорбушки & мосол
снаряжайся && добудь 
глухаря | куропатку | кого-нибудь
не смогешь << винить 
я должон /2 казнить 
государственное дело && /3 улавливаешь нить 
нешто я ~~ пойму
при моем /+2 уму
чай ~ лаптем
щи /(-1 +2) хлебаю 
!Соображаю !что !чему
получается && (+на | !мне)
!!политика 
title:(в стране)
url:ptici.narod.ru/ptici/kuropatka.htm
беспременно inurl:vojne 
host:lib.ru 
rhost:ru.lib.*
site:http://www.lib.ru/PXESY/FILATOW 
mime:pdf
lang:en
domain:ru
date:200712*
date:20071215..20080101, date:>20091231 
cat:11000051

**Comment by andreastt** [comment]
If you press . (dot) outside of a content-editable or textual input field the in-page-search will popup.
