### ISSUE TITLE
No response in a timely manner on Opera 11.51 (Windows) 

### ISSUE THREAD

**Issue by patelm5** [operasoftware/operaprestodriver#64]
see - https://github.com/operasoftware/operadriver/issues/17

No solution yet for windows other than delete a file somewhere? Can someone please clarify the fix?

**Comment by andreastt** [comment]
I'd recommend upgrading to a more recent Opera versions.  Newer Operas allows OperaDriver to specify the profile directory to use, meaning we can start with a fresh profile every time, effectively resolving that issue.
