### ISSUE TITLE
Need a C# port for Opera driver for Selenium

### ISSUE THREAD

**Issue by asudipto** [operasoftware/operaprestodriver#65]
Hi,

I'm learning Selenium using C#.

Is it possible to get a C# port of the Opera driver for Selenium..

I have Opera 11.61

Sudipto.

**Comment by andreastt** [comment]
Please see the documentation available here:

http://seleniumhq.org/docs/03_webdriver.html

http://code.google.com/p/selenium/wiki/RemoteWebDriver

http://selenium.googlecode.com/svn/trunk/docs/api/dotnet/index.html

Essentially you can use OperaDriver in C# by using it as a remote WebDriver.
