### ISSUE TITLE
Using OperaDriver with proxy settings

### ISSUE THREAD

**Issue by mexicano** [operasoftware/operaprestodriver#68]
Hi,

how to start Opera via RemoteWebDriver with proxy settings?

this does not work

``` java
DesiredCapabilities cap = DesiredCapabilities.opera();
Proxy proxy = new Proxy();
proxy.setHttpProxy(proxyHost + ":" + proxyPort);
cap.setCapability(CapabilityType.PROXY, proxy);
RemoteWebDriver wd = new RemoteWebDriver(wdURL, cap);
```

and this too:

``` java
DesiredCapabilities cap = DesiredCapabilities.opera();
Proxy proxy = new Proxy();
proxy.setProxyAutoconfigUrl(proxyAutoconfig);
cap.setCapability(CapabilityType.PROXY, proxy);
RemoteWebDriver wd = new RemoteWebDriver(wdURL, cap);
```

Sergey

**Comment by andreastt** [comment]
Currently OperaDriver does not support using it via proxy.  This is entirely because I haven't gotten around to implement it yet, so please feel free to submit a patch for this! (-:

**Comment by lkende** [comment]
I got around this issue by using setting values in the preferences file. (You might be able to set these in a profile first as well)

You can use Opera's preference editor, or what I did here was build my own preference editor... the commands below won't detail that piece but you can see the top-level area of the file [Proxy] and then the two fields that need to be set.

//auto proxy configuration url
prefsEditor.setPref("Proxy","Use Automatic Proxy Configuration","1");
prefsEditor.setPref("Proxy","Automatic Proxy Configuration URL","http://url-of-proxy-pac");

**Comment by andreastt** [comment]
A very simple patch would be to set those preference directly after launch if they exist in the capabilities object in OperaDriver (-:

**Comment by andreastt** [comment]
OperaDriver 0.16 introduced support for Selenium's Proxy API.
