### ISSUE TITLE
Test automatic downloads via selenium2 

### ISSUE THREAD

**Issue by andywuest** [operasoftware/operaprestodriver#7]
Hi,
in my selenium testcase i need to download files automatically in my testcase. It should be possible
to configure the opera driver in a way, so the download dialog does not show up, and the file is automatically
downloaded and written to a configurable directory.
Ideally the download directory and the enabling/disabling of the download dialog should be configurable
via the operadriver and the java api (for example just like for the firefox profile):

for firefox i can configure all pdf dowloads to be saved directely to a directory. it would be nice, if 
opera would support that as well.

 firefoxProfile.setPreference("browser.download.dir", TMP_DIR);
 firefoxProfile.setPreference("browser.download.folderList", 2);
 firefoxProfile.setPreference("browser.download.defaultFolder", TMP_DIR);
 firefoxProfile.setPreference("browser.helperApps.neverAsk.saveToDisk", "application/pdf");

cheers,
andy

**Comment by Stuk** [comment]
Sadly it's not possible to disable the download dialog from code. But you can do it through Opera:
- Start Opera with `-autotestmode` (see the Readme under Test profile) click on the file and select the "Remember choice..." option.
- Go to Menu > Settings > Preferences > Advanced > Downloads
- Click Add to add your filetype, set to Save to disc and not to ask for folder
- These settings will be saved in your autotest profile, in the operaprefs.ini.

Sorry it's more difficult.

**Comment by andywuest** [comment]
Hi, 
thanks for the hints. I did have a look at the sources and found the following: 
The OperaDriver class has a public setPref Method which looks like what i have been looking for. however it seems not to be possible to set certain values. i tried:
    operaDriver.setPref("User Prefs", "Startup Type", "4");
    operaDriver.setPref("File Types Extension", "application/pdf", "C:\temp,130");

which resulted in the following error. so i am wondering what is the purpose of the public setPref method?

17.06.2011 20:21:42 com.opera.core.systems.scope.stp.StpConnection processMessage
SCHWERWIEGEND: Error : service: "prefs"
commandID: 3
format: 0
status: 3
tag: 17
8: "\n%Could find pref, or pref not writable"

17.06.2011 20:21:42 com.opera.core.systems.WaitState onException
INFO: Got exception

finally i found a way to set the preferences using my own ini writer (using init4j), code looks like.
the code has to be called before creating the opera driver instance, of course.

``` java
    final OperaPreferenceWriter operaPreferences = new OperaPreferenceWriter(
        "C:/Programme/Opera/profile-autotest/operaprefs.ini");
    operaPreferences.setPreference("File Types Extension", "application/pdf", "C:\\temp,130");
    operaPreferences.setPreference("User Prefs", "Startup Type", "4");
    operaPreferences.save();
```

unfortunately i did not find a proper way to overwrite a method that will update the preference file accordingly.
is there a way to make the OperaDriver call my own init method so i can update the pref file on disk?

is it possible to get the full qualified path to the opera preference file, so i do not have to hardcode it my source?

**Comment by Stuk** [comment]
Hi Andy,

The setPref method uses an internal API to set the preferences. The prefs that can be set through the api can be seen by using `listPrefs(boolean sort, String section)` with any of the sections listed [here](https://github.com/operasoftware/operawatir/blob/master/lib/operawatir/preferences.rb#L110). Sadly the "File Types Extension" prefs aren't exposed in the API which we're asking to be fixed, which will help solve this problem.

You could extend and override the `init()` method, making sure to call `super.init();` at the end. There's no general way, but on Windows the profile will be in the same directory as `settings.getOperaBinaryLocation()` (although this is hopefully going to change in the future as we move it to a more writable location)
