### ISSUE TITLE
Invalid coordinates on click after moveto

### ISSUE THREAD

**Issue by eliseosoto** [operasoftware/operaprestodriver#70]
Hi,

I'm using OperaDriver as part of Selenium Server and I interact with Opera via the JsonWire Protocol.

According to the documentation for [/click](http://code.google.com/p/selenium/wiki/JsonWireProtocol#/session/:sessionId/click):

> Click any mouse button (at the coordinates set by the last moveto command).

However that throws an exception:

> org.openqa.selenium.interactions.InvalidCoordinatesException: Invalid coordinates to click on
> Build info: version: '2.20.0', revision: '16008', time: '2012-02-27 19:03:04'
> System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.7.3', java.version: '1.6.0_29'
> Driver info: driver.version: unknown
>     at com.opera.core.systems.OperaMouse.getPoint(OperaMouse.java:88)
>     at com.opera.core.systems.OperaMouse.click(OperaMouse.java:36)... etc, etc

These are the steps to reproduce the issue (HTTP method, URL and Request Body):
1. POST: /session
   
   BODY: {"desiredCapabilities":{"browserName":"opera"}}
2. POST: /session/:sessionId/url
   
   BODY: {"url": "http://fiddle.jshell.net/eliseosoto/UgHpJ/11/show/light/"}
3. POST: /session/:sessionId/element
   
   BODY: {"using": "xpath", "value": "//*[@id='addMessage']"}
4. POST: /session/:sessionId/moveto
   
   BODY: {"element": "0"}
5. POST: /session/:sessionId/click
   
   BODY: {"button": 0}

In step 4 I'm using [/moveto](http://code.google.com/p/selenium/wiki/JsonWireProtocol#/session/:sessionId/moveto) to move to the button, I'm only specifying the element id so according to the docs it should move to the middle of the element.

Step 5 attempts to perform a left click  (button 0) and that's when I get the exception.

I've tried the same steps with ChromeDriver and FirefoxDriver and it works fine.

The only way I've found to click on Opera is to do this but it's not ideal in my case, nevertheless Opera should follow the JsonWire Protocol in a consistent manner.

POST /session/:sessionId/element/0/click

**Comment by andreastt** [comment]
This should be fixed by d0fdd6bb36 and will be in 0.12.
