### ISSUE TITLE
OperaDriver sets font color in console to white (light gray)

### ISSUE THREAD

**Issue by papousek** [operasoftware/operaprestodriver#74]
I use white background in my console and after I run tests using OperaDriver I must reset its state, because the OperaDriver sets font color to white (light gray) and the text isn't readable.

I suggest to avoid setting the font color in OperaDriver.

**Comment by andreastt** [comment]
My console also has a white background, but I've never experienced this.  Can you tell me where this might happen?

**Comment by papousek** [comment]
I get the behaviour when the logging level is set to 'ALL' (or 'FINE', 'FINER', 'FINEST'). My environment is Fedora 15 and Java 1.7.0_04-b20).

**Comment by andreastt** [comment]
I suspect that this happens in the standalone C++ wrapper called launcher (shipped alongside OperaDriver) then.  I've recompiled these to not use colours, and a recent version of OperaDriver shouldn't have this issue.
