### ISSUE TITLE
`ant test` doesn't run cleanly out of the box

### ISSUE THREAD

**Issue by illicitonion** [operasoftware/operaprestodriver#76]
NavigationTest#testHttpRedirect depends on http://t/core/bts/javascript/CORE-26410/003-2.php resolving and being present

All of the following fail with both 11.62 Build 1347 and 12.00 beta Build 1406 on Mac OSX 10.6.8 at commit 3d3d83e7b5bf064f56e853f2635be231dbbf96d7 (no local changes):

OperaSettingsTest#{productIsDesktop,supportsPdIsTrueByDefault}
OperaSettingsIntegrationTest#{profileIsRespected,portSetToDefaultIdentifier,testSettingPort}
OperaDriverTest#testDefaultPort
OperaRunnerTest#{testConstruction,testConstructionWithProfile,testConstructionWithPort}
OperaSettingsCapabilitiesTest#productHasOperaProductDesktopAsDefaultValue

**Comment by andreastt** [comment]
NavigationTest no longer relies on external resources.
