### ISSUE TITLE
new OperaSettings() leads to NPE on windows 7 64 bit with 32 bit IBM JDK6

### ISSUE THREAD

**Issue by yunbugg** [operasoftware/operaprestodriver#79]
Hi,

When using opera driver 0.13/0.14, the invocation to new OperaSettings() lead to NPE:

Exception in thread "main" java.lang.NullPointerException
    at java.io.File.<init>(File.java:233)
    at com.opera.core.systems.OperaSettings$Capability$3.getDefaultValue(OperaSettings.java:155)
    at com.opera.core.systems.OperaSettings$Capability$3.getDefaultValue(OperaSettings.java:153)
    at com.opera.core.systems.OperaSettings$CapabilityInstance.<init>(OperaSettings.java:534)
    at com.opera.core.systems.OperaSettings.<init>(OperaSettings.java:572)

The opera installation is in "C:\Program Files\Opera\opera.exe" however the 32 bit IBM JDK System.getenv("ProgramFiles(x86)") does return C:\Program Files (x86) which leads OperaPaths.operaPath() to search for for opera in a wrong location.

In addition, it may be possible for a windows 64 bit user to install an opera 32 bit browser(I have not confirm this). It may be safer for the opera driver to search for the opera installation in both Program File/Program Files (x86) locations.

**Comment by lkende** [comment]
FYI, I have found the OperaDriver to be more dependable when passing in the path to the Capabilities object using opera.binary.  For Windows, I don't pass it file paths with spaces ever.  Run "dir /x" at c:\ to get short paths.   Hence both 32-bit and 64-bit version of Opera can be referenced as such:

//these paths should be double-backslashed but github is only displaying one
String pathToOpera32 = "C:\PROGRA~2\Opera\Opera.exe"; //goes to Program Files (x86)
String pathToOpera64 = "C:\PROGRA~1\Opera\Opera.exe"; //goes to Program Files for 64-bit browser

DesiredCapabilities capabilities = DesiredCapabilities.opera();
capabilities.setCapability("opera.binary", pathToOpera32 ); //could change to 64bit path

//Opera versions from 11.00 through 11.52 require these extra settings
if (operaMinorVersion < 52){
    capabilities.setCapability("opera.port", -1);
    capabilities.setCapability("opera.profile", "");
    capabilities.setCapability("opera.arguments","-autotestmode"); //this made the difference on 11.52 with latest OperaDriver
}

driver = new OperaDriver(capabilities); 

Hope that helps!

Luke

**Comment by andreastt** [comment]
This should be fixed by the introduction of OperaBinary back in version 0.16.
