### ISSUE TITLE
Creating a new RemoteWebDriver instance with the given session id throws BindException

### ISSUE THREAD

**Issue by papousek** [operasoftware/operaprestodriver#80]
Hi,

we try to reuse sessions from the previous test execution to speed-up test development. The browser doesn't have to start from the scratch and only a driver instance is created (see http://arquillian.org/blog/2012/06/27/arquillian-extension-drone-1-1-0-CR1/).

However OperaDriver is not able to reuse the session (the session is reused here: https://github.com/arquillian/arquillian-extension-drone/blob/master/drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/remote/reusable/ReusableRemoteWebDriver.java#L78) and throws java.net.BindException: Address already in use.

The full stack trace is available here: https://gist.github.com/3088879.

**Comment by illicitonion** [comment]
This is by design; the fact that sessionId is a field only settable by reflection is an indication that this isn't intended to be possible.

If you want to reuse the browser, keep a reference to the WebDriver object, and pass that around between the places you want to share it.

**Comment by papousek** [comment]
Thank you for a quick response. The problem is I want to share the session among the executions (not among the tests in one execution). The use case is: test development/debugging of failed tests.

I understand it's design decision and the sessionId hidden from API, but it can increase the productivity.

**Comment by illicitonion** [comment]
I'll leave this open in case Andreas has any operadriver-specific ideas here

**Comment by andreastt** [comment]
After you've closed the Scope connection there is no way to programmatically open it again without restarting the binary.  You can reconnect manually, but that would involve going to the opera:debug page and hitting "Connect".
