### ISSUE TITLE
Mobile Emulator not found

### ISSUE THREAD

**Issue by eliasnogueira** [operasoftware/operaprestodriver#83]
Hello!
I'm try use and understand Opera Mobile Driver with Mobile Emulator running a WebDriver script, like I found on this blog post http://dev.opera.com/articles/view/introducing-mobile-browser-automation/

What happens
When I try to run the following code I receive an error:  "Exception in thread "main" java.lang.IllegalStateException: The executable is a directory: /Applications/Opera Mobile Emulator.app"

Code:

``` java
DesiredCapabilities dc = DesiredCapabilities.opera();
dc.setCapability("opera.product", OperaProduct.MOBILE);
dc.setCapability("opera.binary", "/Applications/Opera Mobile Emulator.app");

WebDriver driver = new OperaDriver(dc);
```

I'm using operadriver v1.1

Best regards!

**Comment by frdelrosario** [comment]
I had the same trouble myself. With Andreas Tolf Tolfsen's help, I set
opera.binary successfully to:

/Applications/Opera\ Mobile\ Emulator.app/Contents/
Resources/Opera\
Mobile.app/Contents/MacOS/Opera\ Mobile

Opera and the Mobile Emulator are in the default locations, so I imagine
it'll work for you, too.

**Comment by andreastt** [comment]
The package setup for Mac is kind of strange.  There are two binaries in there, one for the emulator configuration and the other the emulator itself.  Setting opera.binary to the second will work on Mac, but unfortunately it's kind of hidden away inside the Resource directory as frdelrosario points out (-:

**Comment by eliasnogueira** [comment]
Thanks guys!
I tried to reach /Applications/Opera Mobile Emulator.app/Contents/Resources/Opera Mobile.app/Contents/MacOS/operamobile but I get failed.
The path from frdeirosario worked fine!
