### ISSUE TITLE
OperaDriver should extend RemoteWebDriver

### ISSUE THREAD

**Issue by andywuest** [operasoftware/operaprestodriver#9]
Plase make the OperaDriver class extend the RemoteWebDriver class, because this class contains all the interfaces needed for testing. In my testcases i want to switch between the driver implementations with a system property switch and i do not want to have different implementations. 

Using the RemoteWebDriver i can write my tests independent of the Driver implementation. since the OperaDriver implements directly i cannot use it directly. i have to introduce a custom Interface and extends all DriverClasses that i use with something like:

``` java
public interface Driver extends TakesScreenshot, FindsByClassName, HasInputDevices, ........ {

}
```

with this interface i can write my test driver independent. 

Extending the RemoteWebDriver should not be that difficult i think, all the additional interface methods that need to be implemented or do not work should throw a NotYetImplemented exception or something like that. or did i miss something?

**Comment by Stuk** [comment]
Now fixed in OperaDriver 0.5
